HouseIndices:
  Kettle:
    appliance_mean_on_power: 2000
    train_houses_ind: [4, 5, 6, 7, 8, 9, 12, 13, 15, 19]
    test_houses_ind: [2, 20]
  Microwave:
    appliance_mean_on_power: 900
    train_houses_ind: [4, 6, 8, 9, 10, 12, 13, 15, 17, 18, 19]
    test_houses_ind: [2, 20]
  WashingMachine:
    appliance_mean_on_power: 500
    train_houses_ind: [1, 5, 6, 7, 8, 9, 10, 13, 15, 16, 17, 18, 19]
    test_houses_ind: [2, 20]
  Dishwasher:
    appliance_mean_on_power: 900
    train_houses_ind: [1, 5, 6, 7, 9, 10, 13, 15, 16, 18]
    test_houses_ind: [2, 20]